---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
  message = FALSE
)
```

# minionator

<!-- badges: start -->
<!-- badges: end -->

The goal of minionator is to ...

## Installation

You can install the released version of minionator from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("minionator")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r l}
library(minionator)

(l <- discrete_matrix(3, 3, 0:2))
```

```{r row_latin}
library(tidyverse)

(row_latin <- tribble(
  ~constraint,             ~variables,
    "alldiff", l %>% filter(row == 0),
    "alldiff", l %>% filter(row == 1),
    "alldiff", l %>% filter(row == 2)
))
```

```{r col_latin}
(column_latin <- tribble(
  ~constraint,             ~variables,
    "alldiff", l %>% filter(col == 0),
    "alldiff", l %>% filter(col == 1),
    "alldiff", l %>% filter(col == 2)
))
```

```{r latin}
(latin <- list(
          variables = l,
             search = "PRINT ALL",
  unary_constraints = bind_rows(row_latin, column_latin)
))
```
```{r minion_output}
minion_output(latin)
```


